### ISSUE TITLE
可以增加一个BlurLayout吗？

### ISSUE THREAD

**Issue by ghost** [nbwzlyd/realTimeBlurView2#1]
如题，如果直接是view的话在这个view之上的控件也会被模糊到，https://github.com/CameraKit/blurkit-android 这个有bug，有些地方会不模糊...

**Comment by nbwzlyd** [comment]
hi，你的意思是，如果一个View上有一个button，然后这个View需要对一个背景图进行高斯模糊，同时View这个button也被高斯模糊掉吗？如果是这个意思，没必要写blurLayout，你可以把这个库直接覆盖在这个View之上，像普通布局一样，因为这个库会把自己层级下面的View全部高斯模糊的。这样就达到了模糊View之上的控件功效。

**Comment by ghost** [comment]
@nbwzlyd 好的感谢回复
